name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Disable shallow clones for better analysis

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1.3  # Use stable version
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y
          trivy fs .

      - name: Docker build and push
        run: |
          docker build --build-arg TMDB_V3_API_KEY=05065cb5e79e57ff40ecd34792c2dc6b -t adeshina100/netflix .
          docker tag adeshina100/netflix:latest adeshina100/netflix:latest
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push adeshina100/netflix:latest
        env:
          DOCKER_CLI_ACI: 1

  deploy:
    name: Deploy
    needs: build  # Ensure consistency with job names
    runs-on: ubuntu-latest  # Change to ubuntu-latest if aws-netflix isn't a defined runner
    steps:
      - name: Pull the Docker image
        run: docker pull adeshina100/netflix:latest

      - name: Trivy image scan
        run: trivy image adeshina100/netflix:latest

      - name: Run the container netflix
        run: docker run -d --name netflix -p 8081:80 adeshina100/netflix:latest
